config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :docs #creation de toutes les ressources, create, delete, update dans routes
  get 'welcome/index'

  authenticated :user do
    root "docs#index",  as: "authenticated_root" #pour les user authentifiés, le root est docs#index
  end

  root 'welcome#index'

 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user #un document a des utilisateurs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy] # executer une methode action avant les actions show, edit update

  def index
    #@doc = Doc.all.order("created_at DESC")
    @doc = Doc.where(user_id: current_user) #Doc.all.order(updated_at: :desc)
  end

  def show
  end

  def new
    @doc = current_user.docs.build #Doc.new
  end

  def create
    @doc = current_user.docs.build(doc_params) #Doc.create(doc_params)
   if @doc.save
    redirect_to @doc
   else
    render :new
   end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
     else
      render :edit
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

  def find_doc
    @doc = Doc.find(params[:id])
  end

  def doc_params
    params.require(:doc).permit(:title, :content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f| 
  = f.input :title, label: 'Titre du livre  '
  = f.input :content , label: 'Contenu du livre  '
  = f.button :submit, class: "button" 

app/views/docs/edit.html.haml
.wrapper_with_padding
  %h1 Modification d'un  document

  =  render 'form'
  %button= link_to "Annuler ",  doc_path, class: "button"

app/views/docs/index.html.haml
.wrapper_with_padding 
  #docs.clearfix
    - unless @doc.blank?
      - @doc.each do |doc|
        %a{href: (url_for [doc])}
          .doc
            %p.title= link_to doc.title, doc
            %p.date= time_ago_in_words(doc.created_at) #permet de recuperer le timestamp de creation dans la base
            %p.content= truncate(doc.content){ link_to "Continue", "#" }
    - else
      %h2 Creation du document 
      %p debut de la creation du document   
      %button= link_to "Création d'un livre ", new_doc_path, class: "button" 

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 Nouveau document
  =  render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %h.title= @doc.title
    %p= simple_format(@doc.content)
    
    .buttons
      = link_to "modifier les documents", edit_doc_path(@doc), class: "button"
      = link_to "effacer les documents", doc_path(@doc), method: :delete, data:{confirm: "etes-vous sur ?"},  class: "button"

app/views/layouts/application.html.haml
%html
%head
  %title FileCabinet   |  C'est mon travail 
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags 
  = csp_meta_tag
%body
  %header
    .header_inner
      = link_to "FileCabinet", root_path, id: "logo"

      %nav
        - if user_signed_in?
          = link_to "Creation Document", new_doc_path
          = link_to "Deconnexion", destroy_user_session_path, method: :delete
        - else
          = link_to "Connexion", new_user_session_path
  %p.notice= notice
  %p.alert= alert

  = yield

app/views/welcome/index.html.haml
#banner
  .banner_content 
    %h1 File Cabinet 
    %p Votre travail, Organisation, tous les jours
    %button= link_to "Entrer", new_user_registration_path 

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organisation
        %p Curabitur eu imperdiet lacus. Praesent leo ipsum, condimentum sit amet sapien eu, dignissim varius nibh. Cras sollicitudin dolor leo, in ornare lectus iaculis eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam luctus massa augue, in suscipit elit cursus eget. Aenean ipsum orci, finibus vel lacinia ac, facilisis non neque. Nunc ut finibus elit. Nam tincidunt ut velit a fermentum. Vivamus dictum volutpat egestas. Etiam vitae eros eu ligula hendrerit ultrices. Nunc ornare non sapien sit amet auctor. Phasellus et volutpat tellus. Maecenas eu viverra nibh.

#bottom_cta
  .wrapper
    %h2 Go !!
    %br
    %button= link_to "Rejoindre Maintenant", new_user_registration_path